version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=w00t
      - MYSQL_DATABASE=shippers_test

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Edge Port
    environment:
      - SERVICES=secretsmanager
